exit 1 for failure

diff --git a/.github/workflows/fail-if-not-default-branch.yaml b/.github/workflows/fail-if-not-default-branch.yaml
--- a/.github/workflows/fail-if-not-default-branch.yaml
+++ b/.github/workflows/fail-if-not-default-branch.yaml
@@ -13,6 +13,6 @@ jobs:
       run: |
         DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
         if [[ "${{ github.ref }}" != "$DEFAULT_BRANCH" ]]; then
-          echo "Branch is not default branch ($DEFAULT_BRANCH), exiting."
-          exit 0
+          echo "Branch is not default branch ($DEFAULT_BRANCH), exiting with failure"
+          exit 1
         fi
