test

diff --git a/.github/workflows/template-build.yaml b/.github/workflows/template-build.yaml
--- a/.github/workflows/template-build.yaml
+++ b/.github/workflows/template-build.yaml
@@ -36,4 +36,10 @@ jobs:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: ${{ inputs.service}}
           IMAGE_TAG: ${{ inputs.image_tag}}
-        run: scripts/build.sh
+        run: |
+          if [[ -z $GH_TOKEN ]]; then
+            echo "Missing required var GH_TOKEN"
+            exit 1
+          fi
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg githubUsername=hbh-github --build-arg githubToken=$GH_TOKEN .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
