check that we can get commit sha

diff --git a/.github/workflows/template-build.yaml b/.github/workflows/template-build.yaml
--- a/.github/workflows/template-build.yaml
+++ b/.github/workflows/template-build.yaml
@@ -95,7 +95,16 @@ jobs:
           ECR_TAG: ${{ inputs.ecr_tag }}
         run: |
           if [ -z "$ECR_TAG" ]; then
-            echo "building and pushing to: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+            echo "Retagging $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG with $ECR_TAG"
+
+          IMAGE_META="$(aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG 2> /dev/null || echo 'Image not found')"
+
+          if [[ "$IMAGE_META" == *"Image not found"* ]]; then
+              echo "The image $IMAGE_TAG does not exist in the repository $REPOSITORY."
+          else
+              echo "The image $IMAGE_TAG exists in the repository $REPOSITORY."
+          fi
+
             REPO_TAG=$IMAGE_TAG
           else
             echo "building and pushing to: $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_TAG"
